name 'redhat_subscription_manager'
maintainer 'Chef Partner Engineering'
maintainer_email 'partnereng@chef.io'
license 'Apache-2.0'
description 'Provides custom resources to interact with Red Hat Subscription Manager (RHSM) and Red Hat Satellite'
long_description 'Provides custom resources to interact with Red Hat Subscription Manager (RHSM) and Red Hat Satellite'
version '1.0.4'
source_url 'https://github.com/chef-partners/redhat-subscription-manager-cookbook'
issues_url 'https://github.com/chef-partners/redhat-subscription-manager-cookbook/issues'
supports 'redhat'
chef_version '>= 12.7' if respond_to?(:chef_version)
